// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _06_ASPNET.Data;

#nullable disable

namespace _06_ASPNET.Migrations
{
    [DbContext(typeof(MujContext))]
    [Migration("20250409125632_Tadek")]
    partial class Tadek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_06_ASPNET.Models.BMI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BmiKategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BmiVysledek")
                        .HasColumnType("float");

                    b.Property<double>("Vaha")
                        .HasColumnType("float");

                    b.Property<double>("Vyska")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BmiModely");
                });

            modelBuilder.Entity("_06_ASPNET.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BMIId")
                        .HasColumnType("int");

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BMIId");

                    b.ToTable("Uzivatele");
                });

            modelBuilder.Entity("_06_ASPNET.Models.Uzivatel", b =>
                {
                    b.HasOne("_06_ASPNET.Models.BMI", "BMI")
                        .WithMany()
                        .HasForeignKey("BMIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BMI");
                });
#pragma warning restore 612, 618
        }
    }
}
